# Generated by Django 5.1.15 on 2026-09-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('OPENAI', 'OpenAI'), ('NVIDIA_NIM', 'NVIDIA NIM'), ('GEMINI', 'Gemini'), ('FAKE', 'Fake (test-only)')], max_length=20)),
                ('base_url', models.CharField(blank=True, help_text="Overrides the adapter's default base URL. Leave blank to use the default.", max_length=500)),
                ('credential_env_var', models.CharField(blank=True, help_text="Name of the environment variable holding this provider's API credential. The credential value itself is never stored in the database (NFR-003).", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text="Provider-specific model identifier, e.g. 'gpt-4o-mini'.", max_length=200)),
                ('supports_structured_output', models.BooleanField(default=False)),
                ('supports_streaming', models.BooleanField(default=False)),
                ('supports_reasoning', models.BooleanField(default=False)),
                ('max_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llm_provider.llmprovider')),
            ],
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('MEMORY_BUILD', 'Memory Build'), ('AJ_ANALYZE', 'Agent Jobber - Analyze'), ('AC_MATCH', 'Agent Candidate - Match'), ('AB_BUILD', 'Agent Builder - Build')], max_length=20)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cached_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_category', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Sanitized message only -- never raw provider request/response content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to='llm_provider.llmmodel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to='llm_provider.llmprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageModelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('MEMORY_BUILD', 'Memory Build'), ('AJ_ANALYZE', 'Agent Jobber - Analyze'), ('AC_MATCH', 'Agent Candidate - Match'), ('AB_BUILD', 'Agent Builder - Build')], max_length=20, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_assignments', to='llm_provider.llmmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='llmmodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_id'), name='unique_provider_model_id'),
        ),
    ]
