# Generated by Django 5.1.15 on 2026-09-08 21:03

import django.contrib.postgres.fields
import django.db.models.deletion
import llm_provider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_applications', '0002_stagerun_max_output_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('adapter_type', models.CharField(choices=[('OPENAI', 'OpenAI'), ('NVIDIA_NIM', 'NVIDIA NIM'), ('GEMINI', 'Gemini'), ('OPENROUTER', 'OpenRouter'), ('FAKE', 'Fake (test-only, no network)')], max_length=20)),
                ('base_url', models.CharField(blank=True, default='', help_text="Overrides the adapter's default base URL (LLM-009). Blank uses the adapter default.", max_length=500)),
                ('credential_env_variable', models.CharField(blank=True, default='', help_text="Name of the environment variable holding this provider's API credential. The credential value itself is never stored in the database (LLM-012). Required for every adapter_type except FAKE.", max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='Whether any model under this provider may be selected for a new StageModelAssignment or a manual/console call. Never deletes a provider row or its LLMModel/LLMCallLog history -- a retired provider is disabled instead.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_identifier', models.CharField(help_text="Provider-specific model identifier, e.g. 'gpt-4o-mini'.", max_length=200)),
                ('supports_structured_output', models.BooleanField(default=False)),
                ('supported_reasoning_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NONE', 'None (reasoning disabled)'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('XHIGH', 'Extra high')], max_length=10), default=llm_provider.models._default_supported_reasoning_levels, help_text="Canonical source of truth for this model's reasoning capability (V2-D034). Always includes NONE. A model with no real reasoning capability stores only [NONE].", size=None)),
                ('max_output_tokens', models.PositiveIntegerField(blank=True, help_text="Provider/model capability ceiling -- the most output tokens this model can ever return. A StageModelAssignment's default_max_output_tokens may never exceed this.", null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this model may still be selected for a new StageModelAssignment or a manual/console call. Never deletes a model row or its LLMCallLog history -- a retired model is disabled instead, preserving referential/audit integrity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llm_provider.llmprovider')),
            ],
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('AJ_ANALYZE', 'AJ Analyze'), ('AC_ASSESS', 'AC Assess'), ('APS_POSITION', 'APS Position'), ('AB_PLAN', 'AB Plan'), ('AB_DRAFT', 'AB Draft'), ('AB_CRITIQUE', 'AB Critique'), ('AB_REFINE', 'AB Refine'), ('QUALITY_EVAL', 'Quality Evaluator')], max_length=40)),
                ('resolved_model_identifier', models.CharField(blank=True, default='', help_text='Only set when a provider reports a concrete model identifier different from requested_model.model_identifier (e.g. an alias/router resolution). Blank when no call has been made or the provider echoed the same identifier -- this app never performs automatic provider/model fallback, so this is provenance, not routing.', max_length=200)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cached_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('finish_reason', models.CharField(blank=True, default='', max_length=40)),
                ('error_category', models.CharField(blank=True, choices=[('CONFIGURATION', 'CONFIGURATION'), ('AUTH', 'AUTH'), ('RATE_LIMIT', 'RATE_LIMIT'), ('TIMEOUT', 'TIMEOUT'), ('SCHEMA_VALIDATION', 'SCHEMA_VALIDATION'), ('PROVIDER_INTERNAL', 'PROVIDER_INTERNAL')], default='', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Sanitized message only -- never raw provider request/response content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_call_logs', to='job_applications.stagerun')),
                ('requested_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to='llm_provider.llmmodel')),
                ('requested_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to='llm_provider.llmprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageModelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('AJ_ANALYZE', 'AJ Analyze'), ('AC_ASSESS', 'AC Assess'), ('APS_POSITION', 'APS Position'), ('AB_PLAN', 'AB Plan'), ('AB_DRAFT', 'AB Draft'), ('AB_CRITIQUE', 'AB Critique'), ('AB_REFINE', 'AB Refine'), ('QUALITY_EVAL', 'Quality Evaluator')], max_length=40, unique=True)),
                ('default_reasoning_level', models.CharField(choices=[('NONE', 'None (reasoning disabled)'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('XHIGH', 'Extra high')], default='NONE', max_length=10)),
                ('default_max_output_tokens', models.PositiveIntegerField(blank=True, help_text="Leave blank to use the assigned model's own max_output_tokens capability.", null=True)),
                ('default_temperature', models.FloatField(blank=True, help_text='Leave blank where the model/reasoning combination does not accept temperature.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_assignments', to='llm_provider.llmmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='llmmodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_identifier'), name='unique_provider_model_identifier'),
        ),
    ]
