# Generated by Django 5.1.15 on 2026-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='supports_temperature',
            field=models.BooleanField(default=False, help_text='Whether this model accepts a `temperature` request parameter at all (V2-D042, fail-closed default per V2-D044). Explicit model capability metadata, not inferred from model_identifier/provider -- False until an operator explicitly opts a model in, consistent with supports_structured_output/supported_reasoning_levels.'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='supports_temperature_with_reasoning',
            field=models.BooleanField(default=False, help_text='Whether `temperature` may be combined with a non-NONE reasoning_level for this model (V2-D042, fail-closed default per V2-D044) -- some reasoning-tier models reject temperature entirely once reasoning is enabled. Meaningless (and rejected by clean()) when supports_temperature is False; only consulted when supports_temperature is True and the requested reasoning_level != NONE.'),
        ),
    ]
