# Generated by Django 5.1.15 on 2026-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='supports_temperature',
            field=models.BooleanField(default=True, help_text='Whether this model accepts a `temperature` request parameter at all (V2-D042). Explicit model capability metadata, not inferred from model_identifier/provider.'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='supports_temperature_with_reasoning',
            field=models.BooleanField(default=True, help_text='Whether `temperature` may be combined with a non-NONE reasoning_level for this model (V2-D042) -- some reasoning-tier models reject temperature entirely once reasoning is enabled. Only consulted when supports_temperature is True and the requested reasoning_level != NONE; irrelevant otherwise.'),
        ),
    ]
