# Generated by Django 5.1.15 on 2026-09-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_provider', '0002_alter_llmcalllog_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcalllog',
            name='stage',
            field=models.CharField(choices=[('MEMORY_BUILD', 'Memory Build'), ('AJ_ANALYZE', 'Agent Jobber - Analyze'), ('AC_NORMALIZE', 'Agent Candidate - Requirement Normalization (bounded query expansion, D-015/D-020)'), ('AC_RANK', 'Agent Candidate - Relevance Ranking (D-015 bounded step)'), ('AC_MATCH', 'Agent Candidate - Match'), ('AB_BUILD', 'Agent Builder - Build')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stagemodelassignment',
            name='stage',
            field=models.CharField(choices=[('MEMORY_BUILD', 'Memory Build'), ('AJ_ANALYZE', 'Agent Jobber - Analyze'), ('AC_NORMALIZE', 'Agent Candidate - Requirement Normalization (bounded query expansion, D-015/D-020)'), ('AC_RANK', 'Agent Candidate - Relevance Ranking (D-015 bounded step)'), ('AC_MATCH', 'Agent Candidate - Match'), ('AB_BUILD', 'Agent Builder - Build')], max_length=20, unique=True),
        ),
    ]
