# Generated by Django 5.1.15 on 2026-09-04 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_provider', '0003_alter_llmcalllog_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemodelassignment',
            name='max_output_tokens',
            field=models.PositiveIntegerField(blank=True, help_text="Optional per-stage request budget (2026-09-04, stage-specific token budgets). When set, this stage's requests use this value instead of the assigned model's own max_output_tokens; it must never exceed that model capability. Leave blank to use the model's capability (or a conservative built-in default if the model doesn't declare one) -- the previous, single-budget-per-model behavior.", null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='max_output_tokens',
            field=models.PositiveIntegerField(blank=True, help_text="Provider/model capability ceiling -- the most output tokens this model can ever return, regardless of which stage is calling it. Never a per-stage request budget (see StageModelAssignment.max_output_tokens for that); a stage assignment's own budget may never exceed this value.", null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
