# Generated by Django 5.1.15 on 2026-09-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_provider', '0004_stagemodelassignment_max_output_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='data_collection_policy',
            field=models.CharField(choices=[('DENY', 'Deny (no endpoint that collects/trains on request data)'), ('ALLOW', 'Allow')], default='DENY', help_text="OpenRouter-specific: the privacy value sent as this provider's request-level `provider.data_collection` routing directive. Ignored by every other provider type.", max_length=10),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('NVIDIA_NIM', 'NVIDIA NIM'), ('GEMINI', 'Gemini'), ('OPENROUTER', 'OpenRouter'), ('FAKE', 'Fake (test-only)')], max_length=20),
        ),
    ]
