# Generated by Django 5.1.15 on 2026-09-05 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_provider', '0005_llmprovider_data_collection_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemodelassignment',
            name='read_timeout_seconds',
            field=models.PositiveIntegerField(blank=True, help_text="Optional per-stage HTTP read-timeout override, in seconds (2026-09-05, configurable per-stage timeout). When set, this stage's provider requests use this value instead of the built-in default (see `llm_provider.adapters.base.DEFAULT_READ_TIMEOUT_SECONDS`). Must be between 1 and 300 seconds inclusive. This is the read timeout only -- the connect timeout is a separate, fixed, non-configurable value shared by every stage (`llm_provider.adapters.base.DEFAULT_CONNECT_TIMEOUT_SECONDS`), never the same 'one combined number' the pre-2026-09-05 code passed to every adapter's HTTP call. Leave blank to use the built-in default.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
