# Generated by Django 5.1.15 on 2026-09-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_provider', '0006_stagemodelassignment_read_timeout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='rate_limit_diagnostics',
            field=models.JSONField(blank=True, help_text='Sanitized rate-limit diagnostic metadata (2026-09-05, OpenRouter 429 diagnostics). Populated only for RATE_LIMIT errors where the adapter could extract it from documented, non-secret response headers/metadata -- a small fixed set of keys (retry_after_seconds, limit, remaining, reset, source, upstream_provider), never a raw response body or headers wholesale. Null for every other error/success row and for a RATE_LIMIT row where no such metadata was present.', null=True),
        ),
        migrations.CreateModel(
            name='OpenRouterKeyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('is_free_tier', models.BooleanField(blank=True, null=True)),
                ('limit', models.FloatField(blank=True, null=True)),
                ('limit_remaining', models.FloatField(blank=True, null=True)),
                ('limit_reset', models.CharField(blank=True, max_length=50)),
                ('usage', models.FloatField(blank=True, null=True)),
                ('usage_daily', models.FloatField(blank=True, null=True)),
                ('usage_weekly', models.FloatField(blank=True, null=True)),
                ('usage_monthly', models.FloatField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, help_text='Sanitized failure reason from the last refresh attempt, if it failed. Blank on success.', max_length=300)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openrouter_key_status', to='llm_provider.llmprovider')),
            ],
        ),
    ]
