# Generated by Django 5.1.15 on 2026-09-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_provider', '0007_llmcalllog_rate_limit_diagnostics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='correlation_id',
            field=models.CharField(blank=True, help_text='Optional caller-supplied correlation/workflow identifier (e.g. a JobApplication id), carried through from NormalizedLLMRequest.correlation_id when the caller sets one. Blank when not supplied -- no pipeline call site is required to set this.', max_length=200),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='finish_reason',
            field=models.CharField(blank=True, help_text="The provider's reported finish_reason for a successful call (e.g. 'stop', 'length'). Blank for an error row or when the provider did not report one. A truncated response (finish_reason=length) is never stored as a success row in the first place (llm_provider/adapters/openai.py's parser fails it closed as CONFIGURATION before reaching here) -- this field records the reason for the rows that do succeed, for diagnostic grouping.", max_length=50),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='resolved_model_id',
            field=models.CharField(blank=True, help_text="The actual upstream model id the provider reports it used to serve this call (2026-09-07, requested-vs-resolved audit -- relevant for a virtual router such as OpenRouter's Free Models Router, whose requested slug, e.g. 'openrouter/free', is not the model that actually generated the response). Parsed only from the response's own documented top-level 'model' field when present -- never guessed, never overwriting `model` (the requested LLMModel FK, which always stays exact). Blank when the provider did not report one (e.g. an error response, or a provider whose response shape does not include it).", max_length=200),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Whether this model may still be selected for a new StageModelAssignment or the smoke-test harness's default-model selection (2026-09-07, OpenRouter Free Router migration). Never deletes a model row or its LLMCallLog history -- a retired model (e.g. a superseded OpenRouter slug) is set to False instead, preserving referential integrity and audit history while making rollback (flip this back to True, or reassign a stage to it) a plain registry edit rather than a re-creation. `get_adapter_for_stage` refuses to route a live call to an inactive model (`InactiveModelAssignedError`) so nothing can silently keep calling a deactivated model just because an old StageModelAssignment row still points at it."),
        ),
    ]
