# Generated by Django 5.1.15 on 2026-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_provider', '0008_llmcalllog_correlation_id_llmcalllog_finish_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='selection_source',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'Stage default (StageModelAssignment)'), ('OVERRIDE', 'Explicit per-run override')], help_text="Whether `model` (the requested LLMModel FK above) was resolved from the stage's configured global default or from an explicit per-run operator override. Set by `llm_provider.adapters.get_adapter_for_stage`/`BaseLLMAdapter`; blank for any LLMCallLog row written before this field existed.", max_length=10),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='display_name',
            field=models.CharField(blank=True, help_text="Optional operator-friendly label shown in the AJ/AC/AB model-selection UI in place of the raw model_id (2026-09-07, per-run model selection). Blank means the UI falls back to showing '<provider name> -- <model_id>' -- this field exists only to improve a selector's readability (e.g. 'Free Models Router' for 'openrouter/free'), never to change routing or eligibility, which are always keyed off model_id/provider.", max_length=200),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Whether any model under this provider may be selected for a new StageModelAssignment or offered as a per-run override in the AJ/AC/AB model-selection UI (2026-09-07, per-run model selection / D-038 default-configuration broadening). Mirrors LLMModel.is_active at the provider level -- never deletes a provider row or its LLMModel/LLMCallLog history; a retired provider is deactivated instead, which removes every one of its models from eligibility (llm_provider.services.eligibility) without needing to flip each model individually. Existing rows default to True, so this migration changes no provider's current behavior on its own."),
        ),
    ]
