# Generated by Django 5.1.15 on 2026-09-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_provider', '0009_llmcalllog_selection_source_llmmodel_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemodelassignment',
            name='default_reasoning_effort',
            field=models.CharField(blank=True, choices=[('none', 'None (reasoning disabled)'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'Extra high')], default='', help_text='Optional stage-default reasoning effort (2026-09-07, paid GPT-5.4 model defaults), drawn from the one centrally-validated `ReasoningEffort` enum. Blank means \'send no reasoning request at all\' -- the model/provider\'s own default behavior -- which is distinct from `ReasoningEffort.NONE` (\'explicitly disable reasoning\'), matching OpenRouter\'s own documented distinction between omitting the `reasoning` key and sending `{"effort": "none"}`. A per-run operator override (`llm_provider.services.model_selection.parse_requested_reasoning_effort`) may replace this for one call without ever rewriting this stored default. Must be blank/`NONE` unless `model.supports_reasoning` is True -- see `clean()`.', max_length=10),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='reasoning_effort',
            field=models.CharField(blank=True, choices=[('none', 'None (reasoning disabled)'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'Extra high')], help_text="The resolved `ReasoningEffort` value actually sent for this call (2026-09-07, paid GPT-5.4 model defaults) -- set by `llm_provider.adapters.get_adapter_for_stage`'s resolution, mirroring `selection_source`'s audit role for the model. Blank means no `reasoning` key was sent at all (the resolved model does not support reasoning, or no effort was configured/requested), never confused with `ReasoningEffort.NONE` ('none'), which records a deliberate, explicit suppression of a reasoning-capable model's own default reasoning behavior. Never a raw reasoning trace/thinking-token content -- only the level name.", max_length=10),
        ),
    ]
