# Generated by Django 5.1.15 on 2026-09-08 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('URL', 'URL'), ('PASTED_TEXT', 'Pasted text')], max_length=20)),
                ('source_url', models.URLField(blank=True, default='')),
                ('pipeline_phase', models.CharField(choices=[('NEW', 'New'), ('ANALYSIS', 'Analysis'), ('POSITIONING', 'Positioning'), ('PREPARATION', 'Preparation'), ('READY', 'Ready')], default='NEW', max_length=20)),
                ('application_outcome', models.CharField(choices=[('NOT_APPLIED', 'Not applied'), ('APPLIED', 'Applied'), ('INTERVIEWING', 'Interviewing'), ('REJECTED', 'Rejected')], default='NOT_APPLIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('AJ_ANALYZE', 'AJ Analyze'), ('AC_ASSESS', 'AC Assess'), ('APS_POSITION', 'APS Position'), ('AB_PLAN', 'AB Plan'), ('AB_DRAFT', 'AB Draft'), ('AB_CRITIQUE', 'AB Critique'), ('AB_REFINE', 'AB Refine'), ('QUALITY_EVAL', 'Quality Evaluator'), ('CANDIDATE_CONTEXT_BUILD', 'Candidate Context Build'), ('VALIDATE_DRAFT', 'Validate Draft'), ('VALIDATE_REFINED', 'Validate Refined'), ('GATE_1', 'Human Gate 1'), ('GATE_2', 'Human Gate 2'), ('RENDER', 'Render')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('EDITED', 'Edited'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('raw_structured_output', models.JSONField(blank=True, null=True)),
                ('working_output', models.JSONField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_runs', to='job_applications.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationStageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('AJ_ANALYZE', 'AJ Analyze'), ('AC_ASSESS', 'AC Assess'), ('APS_POSITION', 'APS Position'), ('AB_PLAN', 'AB Plan'), ('AB_DRAFT', 'AB Draft'), ('AB_CRITIQUE', 'AB Critique'), ('AB_REFINE', 'AB Refine'), ('QUALITY_EVAL', 'Quality Evaluator'), ('CANDIDATE_CONTEXT_BUILD', 'Candidate Context Build'), ('VALIDATE_DRAFT', 'Validate Draft'), ('VALIDATE_REFINED', 'Validate Refined'), ('GATE_1', 'Human Gate 1'), ('GATE_2', 'Human Gate 2'), ('RENDER', 'Render')], max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_states', to='job_applications.jobapplication')),
                ('approved_stage_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='job_applications.stagerun')),
                ('current_stage_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='job_applications.stagerun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job_application', 'stage'), name='unique_job_application_stage')],
            },
        ),
    ]
