# Generated by Django 5.1.15 on 2026-09-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_phase', models.CharField(choices=[('NEW', 'New'), ('ANALYSIS', 'Analysis'), ('PREPARATION', 'Preparation'), ('READY', 'Ready')], default='NEW', max_length=20)),
                ('application_outcome', models.CharField(choices=[('NOT_APPLIED', 'Not applied'), ('APPLIED', 'Applied'), ('INTERVIEWING', 'Interviewing'), ('REJECTED', 'Rejected')], default='NOT_APPLIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
