# Generated by Django 5.1.15 on 2026-09-02 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_applications', '0001_initial'),
        ('job_intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='current_jra',
            field=models.ForeignKey(blank=True, help_text='The JobRequirementAnalysis version currently considered authoritative for this application. Set only after a full successful analysis persists (see job_intake.services.intake) -- never points at a partially-built or failed version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='job_intake.jobrequirementanalysis'),
        ),
    ]
