# Generated by Django 5.1.15 on 2026-09-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerun',
            name='max_output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
