# Generated by Django 5.1.15 on 2026-09-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_matching', '0001_initial'),
        ('job_applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='current_fit_assessment',
            field=models.ForeignKey(blank=True, help_text="The FitAssessment version currently considered authoritative for this application (M5). Set whenever a new version is built (initial run or a Gate-1 feedback re-run) -- 'current' tracks the latest version, not necessarily an operator-approved one. Freshness (D-006) compares this pointer's own current_jra_id against JobApplication.current_jra_id, never a timestamp.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='candidate_matching.fitassessment'),
        ),
    ]
