# Generated by Django 5.1.15 on 2026-09-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0002_stagerun_max_output_tokens'),
        ('llm_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerun',
            name='model',
            field=models.ForeignKey(blank=True, help_text='Null for deterministic stages (docs/ARCHITECTURE.md Section 5, V2-D036).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_runs', to='llm_provider.llmmodel'),
        ),
        migrations.AddField(
            model_name='stagerun',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Null for deterministic stages (docs/ARCHITECTURE.md Section 5, V2-D036).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_runs', to='llm_provider.llmprovider'),
        ),
        migrations.AddField(
            model_name='stagerun',
            name='reasoning_level',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('XHIGH', 'XHIGH')], default='', help_text='Blank for deterministic stages.', max_length=10),
        ),
        migrations.AddField(
            model_name='stagerun',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
