# Generated by Django 5.1.15 on 2026-09-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0003_jobapplication_current_fit_assessment'),
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='current_resume_draft',
            field=models.ForeignKey(blank=True, help_text="The ResumeDraft version currently considered authoritative for this application (M6). Set whenever a new version is built -- 'current' tracks the latest version, not necessarily the confirmed one. Freshness (D-006) compares this pointer's own based_on_fit_assessment_id against JobApplication.current_fit_assessment_id.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resume_builder.resumedraft'),
        ),
    ]
