# Generated by Django 5.1.15 on 2026-09-02 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('URL', 'URL'), ('PASTED', 'Pasted text')], max_length=10)),
                ('source_url', models.URLField(blank=True, default='', max_length=2000)),
                ('original_input', models.TextField(help_text='The operator-supplied original input verbatim -- the pasted text, or the URL.')),
                ('extracted_text', models.TextField(help_text='The posting text actually sent for analysis (for PASTED, equals original_input; for URL, the fetched+extracted main content).')),
                ('extracted_text_sha256', models.CharField(editable=False, max_length=64)),
                ('posting_language', models.CharField(max_length=16)),
                ('employer', models.CharField(blank=True, default='', max_length=300)),
                ('role_title', models.CharField(blank=True, default='', max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('work_arrangement', models.CharField(blank=True, default='', max_length=100)),
                ('screening_risks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirement_analyses', to='job_applications.jobapplication')),
            ],
            options={
                'ordering': ['job_application_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=16)),
                ('order', models.PositiveIntegerField(help_text='Deterministic 1-based ordering within this JRA version.')),
                ('category', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('PREFERRED', 'Preferred'), ('RESPONSIBILITY', 'Responsibility'), ('ATS_SIGNAL', 'ATS signal'), ('IMPLIED_EXPECTATION', 'Implied expectation')], max_length=24)),
                ('text', models.TextField()),
                ('source_context', models.TextField(blank=True, default='')),
                ('job_requirement_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='job_intake.jobrequirementanalysis')),
            ],
            options={
                'ordering': ['job_requirement_analysis_id', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobrequirementanalysis',
            constraint=models.UniqueConstraint(fields=('job_application', 'version'), name='unique_jra_version_per_application'),
        ),
        migrations.AddConstraint(
            model_name='jobrequirement',
            constraint=models.UniqueConstraint(fields=('job_requirement_analysis', 'requirement_id'), name='unique_requirement_id_per_jra'),
        ),
        migrations.AddConstraint(
            model_name='jobrequirement',
            constraint=models.UniqueConstraint(fields=('job_requirement_analysis', 'order'), name='unique_requirement_order_per_jra'),
        ),
    ]
