# Generated by Django 5.1.15 on 2026-09-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_matching', '0001_initial'),
        ('job_applications', '0003_jobapplication_current_fit_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('retrieved_claim_ids', models.JSONField(blank=True, default=list)),
                ('retrieved_engagement_ids', models.JSONField(blank=True, default=list)),
                ('recommended_title', models.CharField(max_length=300)),
                ('title_options', models.JSONField(blank=True, default=list, help_text='TargetPositioning.title_options -- internal planning content, never rendered (docs/RESUME_OUTPUT_STRUCTURE.md Sec 5).')),
                ('skill_categories', models.JSONField(blank=True, default=list, help_text="Agent Builder's own broader SkillCategory reasoning workspace -- not independently evidence-checked and never rendered directly; only the SelectedResumeSkills entries (stored as ResumeElement rows, section=SKILL) are validated and rendered.")),
                ('positioning_guidance', models.JSONField(blank=True, default=dict, help_text='PositioningGuidance -- a generation constraint, never independent factual evidence, never rendered.')),
                ('rendered_markdown', models.TextField(help_text='Deterministic markdown rendered from validated ResumeElement rows only, after the no-fabrication validator passed -- never anything Agent Builder emitted directly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('based_on_fit_assessment', models.ForeignKey(help_text='The exact FitAssessment version this draft was built from (D-006 freshness identity -- compared against JobApplication.current_fit_assessment_id, never a timestamp).', on_delete=django.db.models.deletion.PROTECT, related_name='resume_drafts', to='candidate_matching.fitassessment')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_drafts', to='job_applications.jobapplication')),
            ],
            options={
                'ordering': ['job_application_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ResumeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('SUMMARY', 'Professional summary'), ('EXPERIENCE_BULLET', 'Experience bullet'), ('POSITIONING_THEME', 'Positioning theme'), ('ACHIEVEMENT', 'Achievement'), ('SKILL', 'Skill'), ('CERTIFICATION', 'Certification'), ('LANGUAGE', 'Language')], max_length=20)),
                ('engagement_id', models.CharField(blank=True, default='', max_length=32)),
                ('order', models.PositiveIntegerField(help_text='Deterministic ordering within (section, engagement_id).')),
                ('text', models.TextField()),
                ('supporting_memory_claim_ids', models.JSONField(blank=True, default=list)),
                ('matched_job_requirement_ids', models.JSONField(blank=True, default=list)),
                ('resume_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='resume_builder.resumedraft')),
            ],
            options={
                'ordering': ['resume_draft_id', 'section', 'engagement_id', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='resumedraft',
            constraint=models.UniqueConstraint(fields=('job_application', 'version'), name='unique_resume_draft_version_per_application'),
        ),
        migrations.AddConstraint(
            model_name='resumeelement',
            constraint=models.UniqueConstraint(fields=('resume_draft', 'section', 'engagement_id', 'order'), name='unique_resume_element_order'),
        ),
    ]
