# Generated by Django 5.1.15 on 2026-09-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_matching', '0004_agentcandidaterun_agentcandidatestage_and_more'),
        ('job_applications', '0004_jobapplication_current_resume_draft'),
        ('llm_provider', '0010_default_reasoning_effort'),
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBuilderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('READY', 'Ready to run'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('EDITED', 'Edited (operator output differs from provider output)'), ('APPROVED', 'Approved (ResumeDraft created)')], default='READY', max_length=12)),
                ('prepared_input', models.JSONField(blank=True, null=True)),
                ('edited_input', models.JSONField(blank=True, null=True)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('selection_source', models.CharField(blank=True, choices=[('DEFAULT', 'Stage default (StageModelAssignment)'), ('OVERRIDE', 'Explicit per-run override')], max_length=10)),
                ('reasoning_effort', models.CharField(blank=True, max_length=10)),
                ('requested_output_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_output_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_output', models.JSONField(blank=True, null=True)),
                ('provider_output_hash', models.CharField(blank=True, max_length=64)),
                ('operator_output', models.JSONField(blank=True, null=True)),
                ('approved_output', models.JSONField(blank=True, null=True)),
                ('approved_output_hash', models.CharField(blank=True, max_length=64)),
                ('validation_state', models.CharField(blank=True, choices=[('UNVALIDATED', 'Not yet validated'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='UNVALIDATED', max_length=12)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('failure_category', models.CharField(blank=True, max_length=20)),
                ('failure_summary', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on_fit_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_builder_runs', to='candidate_matching.fitassessment')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_builder_runs', to='job_applications.jobapplication')),
                ('llm_call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_builder_runs', to='llm_provider.llmcalllog')),
                ('resulting_resume_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_builder_run', to='resume_builder.resumedraft')),
                ('selected_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='llm_provider.llmmodel')),
                ('selected_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='llm_provider.llmprovider')),
            ],
            options={
                'ordering': ['job_application_id', 'version'],
                'constraints': [models.UniqueConstraint(fields=('job_application', 'version'), name='unique_ab_run_version_per_application'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), ('validation_state', 'VALID'), _connector='OR'), name='approved_ab_run_requires_valid_output')],
            },
        ),
    ]
