# Generated by Django 5.1.15 on 2026-09-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_applications', '0003_jobapplication_current_fit_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(choices=[('GATE_1', 'Gate 1 (Candidate matching)'), ('GATE_2', 'Gate 2 (Resume draft)')], max_length=10)),
                ('target', models.CharField(choices=[('AJ', 'Agent Jobber'), ('AC', 'Agent Candidate'), ('AB', 'Agent Builder')], max_length=10)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_feedback', to='job_applications.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
