# Generated by Django 5.1.15 on 2026-09-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'candidate memories',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_direction', models.TextField(blank=True, default='')),
                ('target_role_families', models.JSONField(blank=True, default=list)),
                ('preferred_positioning', models.TextField(blank=True, default='')),
                ('technical_strengths', models.JSONField(blank=True, default=list)),
                ('domain_strengths', models.JSONField(blank=True, default=list)),
                ('known_gaps', models.JSONField(blank=True, default=list)),
                ('development_areas', models.JSONField(blank=True, default=list)),
                ('technology_depth', models.JSONField(blank=True, default=dict)),
                ('wording_preferences', models.TextField(blank=True, default='')),
                ('privacy_preferences', models.TextField(blank=True, default='')),
                ('employer_naming_preferences', models.TextField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='candidate_memory.candidatememory')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_key', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('CAREER_HISTORY', 'Career history'), ('SKILL', 'Skill'), ('PROJECT', 'Project'), ('ACHIEVEMENT', 'Achievement'), ('EDUCATION', 'Education'), ('CERTIFICATION', 'Certification'), ('LANGUAGE', 'Language'), ('PREFERENCE', 'Preference'), ('GAP_OR_CONSTRAINT', 'Gap or constraint'), ('OTHER', 'Other')], max_length=32)),
                ('confirmation_status', models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='UNREVIEWED', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='candidate_memory.candidatememory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('UNRESOLVED', 'Unresolved'), ('RESOLVED', 'Resolved')], default='UNRESOLVED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='candidate_memory.candidatememory')),
                ('related_claims', models.ManyToManyField(blank=True, related_name='conflicts', to='candidate_memory.memoryclaim')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemorySourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=512)),
                ('source_kind', models.CharField(choices=[('MEMORY_PROFILE', 'AC memory profile'), ('PROFILE_ENGLISH', 'English corpus'), ('PROFILE_GERMAN', 'German corpus'), ('OTHER', 'Other operator source')], max_length=32)),
                ('precedence_rank', models.PositiveSmallIntegerField(help_text='Lower number wins when sources disagree (1 = highest precedence).')),
                ('content_sha256', models.CharField(max_length=64)),
                ('content_text', models.TextField()),
                ('byte_size', models.PositiveIntegerField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='candidate_memory.candidatememory')),
            ],
            options={
                'ordering': ['precedence_rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryClaimSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.TextField()),
                ('location_hint', models.CharField(blank=True, default='', max_length=255)),
                ('char_start', models.PositiveIntegerField(blank=True, null=True)),
                ('char_end', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='candidate_memory.memoryclaim')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_supports', to='candidate_memory.memorysourcedocument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CareerEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role_title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.CharField(blank=True, default='', max_length=64)),
                ('end_date_or_present', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_hint', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_engagements', to='candidate_memory.candidatememory')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_engagements', to='candidate_memory.memorysourcedocument')),
            ],
            options={
                'ordering': ['sort_hint', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperatorCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=255)),
                ('correction_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_corrections', to='candidate_memory.candidatememory')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PositioningHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_or_context', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('was_successful', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positioning_history', to='candidate_memory.candidatememory')),
            ],
            options={
                'verbose_name_plural': 'positioning history entries',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaticResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_metadata', models.JSONField(blank=True, default=dict)),
                ('static_certifications', models.JSONField(blank=True, default=list)),
                ('static_languages', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='static_resume_profile', to='candidate_memory.candidatememory')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('is_primary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('role_title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.CharField(blank=True, default='', max_length=64)),
                ('end_date_or_present', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_engagement', models.ForeignKey(help_text='Source engagement retained for provenance; metadata is copied at creation.', on_delete=django.db.models.deletion.PROTECT, related_name='experience_slots', to='candidate_memory.careerengagement')),
                ('static_resume_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_slots', to='candidate_memory.staticresumeprofile')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='memoryclaim',
            constraint=models.UniqueConstraint(fields=('memory', 'claim_key'), name='unique_memory_claim_key'),
        ),
        migrations.AddConstraint(
            model_name='memoryconflict',
            constraint=models.UniqueConstraint(fields=('memory', 'topic'), name='unique_memory_conflict_topic'),
        ),
        migrations.AddConstraint(
            model_name='memorysourcedocument',
            constraint=models.UniqueConstraint(fields=('memory', 'content_sha256'), name='unique_memory_source_content_hash'),
        ),
        migrations.AddConstraint(
            model_name='memorysourcedocument',
            constraint=models.UniqueConstraint(fields=('memory', 'source_path'), name='unique_memory_source_path'),
        ),
        migrations.AddConstraint(
            model_name='experienceslot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('static_resume_profile', 'sequence'), name='unique_active_primary_slot_sequence'),
        ),
        migrations.AddConstraint(
            model_name='experienceslot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('static_resume_profile', 'career_engagement'), name='unique_active_primary_slot_engagement'),
        ),
    ]
