# Generated by Django 5.1.15 on 2026-09-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('BUILDING', 'Building'), ('NEEDS_REVIEW', 'Needs review'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='BUILDING', max_length=20)),
                ('build_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('base_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_revisions', to='candidate_memory.candidatememory')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='MemoryClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(blank=True, max_length=32)),
                ('stable_key', models.CharField(help_text="Cross-revision identity key -- lets carry-forward say 'this is the same claim as one in base_revision' even if claim_id renumbers.", max_length=100)),
                ('canonical_text_en', models.TextField(help_text='Canonical claim text -- English only (D-015).')),
                ('claim_type', models.CharField(max_length=100)),
                ('subject_scope', models.CharField(help_text='Employer/client/project/context.', max_length=200)),
                ('experience_level', models.CharField(blank=True, choices=[('AWARENESS', 'Awareness'), ('LEARNING', 'Learning'), ('PROTOTYPE', 'Prototype'), ('PROFESSIONAL_DELIVERY', 'Professional delivery'), ('PRODUCTION_OPERATION', 'Production operation'), ('ARCHITECTURE_OWNERSHIP', 'Architecture ownership'), ('LEADERSHIP', 'Leadership')], max_length=30, null=True)),
                ('resume_eligible', models.BooleanField(default=False)),
                ('confirmation_status', models.CharField(choices=[('UNCONFIRMED', 'Unconfirmed'), ('CONFIRMED', 'Confirmed'), ('RETIRED', 'Retired'), ('BLOCKED_CONFLICT', 'Blocked (conflict)')], default='UNCONFIRMED', max_length=20)),
                ('duplicate_group_key', models.CharField(blank=True, max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('legal_employer', models.CharField(blank=True, max_length=200)),
                ('client_organization', models.CharField(blank=True, max_length=200)),
                ('presentation_mode', models.CharField(choices=[('CLIENT_CENTRIC', 'Client-centric (default)'), ('LEGAL_EMPLOYER_EXPLICIT', 'Legal employer explicit'), ('COMBINED', 'Combined')], default='CLIENT_CENTRIC', max_length=30)),
                ('candidate_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='candidate_memory.candidatememory')),
            ],
            options={
                'ordering': ['claim_id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryClaimSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation', models.TextField()),
                ('start_line', models.PositiveIntegerField()),
                ('end_line', models.PositiveIntegerField()),
                ('quotation_hash', models.CharField(editable=False, max_length=64)),
                ('source_language', models.CharField(max_length=10)),
                ('support_role', models.CharField(choices=[('PRIMARY', 'Primary'), ('CORROBORATING', 'Corroborating'), ('GERMAN_EXPRESSION', 'German expression')], max_length=20)),
                ('memory_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='candidate_memory.memoryclaim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemoryConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_key', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('operator_resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='candidate_memory.candidatememory')),
                ('involved_claims', models.ManyToManyField(related_name='conflicts', to='candidate_memory.memoryclaim')),
                ('involved_supports', models.ManyToManyField(blank=True, related_name='conflicts', to='candidate_memory.memoryclaimsupport')),
                ('resolved_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to='candidate_memory.memoryclaim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemorySourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_source_key', models.CharField(help_text="Stable identity for 'this conceptual document' across revisions, independent of filename -- what D-002's unchanged/changed comparison keys off.", max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('source_role', models.CharField(choices=[('PRIMARY_PROFILE', 'Primary profile'), ('ENGLISH_CORPUS', 'English corpus'), ('GERMAN_CORPUS', 'German corpus'), ('OPERATOR_UPDATE', 'Operator update')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('trust_status', models.CharField(choices=[('OPERATOR_APPROVED', 'Operator approved'), ('UNVERIFIED', 'Unverified')], max_length=20)),
                ('precedence', models.PositiveIntegerField(help_text='Lower number = higher precedence.')),
                ('raw_content', models.TextField()),
                ('content_sha256', models.CharField(editable=False, max_length=64)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='candidate_memory.candidatememory')),
                ('unchanged_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carried_forward_to', to='candidate_memory.memorysourcedocument')),
            ],
            options={
                'ordering': ['precedence', 'logical_source_key'],
            },
        ),
        migrations.AddField(
            model_name='memoryclaimsupport',
            name='memory_source_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_supports', to='candidate_memory.memorysourcedocument'),
        ),
        migrations.CreateModel(
            name='CandidateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('CAUTION', 'Caution'), ('PROHIBITION', 'Prohibition'), ('PREFERENCE', 'Preference'), ('POSITIONING', 'Positioning'), ('LEARNING_STATUS', 'Learning status')], max_length=20)),
                ('text', models.TextField()),
                ('scope', models.CharField(blank=True, max_length=200)),
                ('source_quote', models.TextField(blank=True)),
                ('start_line', models.PositiveIntegerField(blank=True, null=True)),
                ('end_line', models.PositiveIntegerField(blank=True, null=True)),
                ('candidate_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='candidate_memory.candidatememory')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='candidate_memory.memorysourcedocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='candidatememory',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('status',), name='unique_active_candidate_memory'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaim',
            constraint=models.UniqueConstraint(fields=('candidate_memory', 'claim_id'), name='unique_claim_id_per_revision'),
        ),
        migrations.AddConstraint(
            model_name='memorysourcedocument',
            constraint=models.UniqueConstraint(fields=('candidate_memory', 'logical_source_key'), name='unique_logical_source_per_revision'),
        ),
    ]
