# Generated by Django 5.1.15 on 2026-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_memory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryclaim',
            name='structured_value',
            field=models.JSONField(blank=True, default=dict, help_text="Optional structured payload for deterministic conflict comparison, e.g. {'location': 'Nuremberg, Germany'} or {'language': 'German', 'level': 'B1'}. Prose (canonical_text_en) remains the resume-facing text; this is comparison data only."),
        ),
    ]
