# Generated by Django 5.1.15 on 2026-09-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_memory', '0002_protect_claim_support_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoryclaimsupport',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='memorysourcedocument',
            options={'base_manager_name': 'objects', 'ordering': ['precedence_rank', 'id']},
        ),
    ]
