# Generated by Django 5.1.15 on 2026-09-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_memory', '0002_memoryclaim_structured_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatememory',
            name='status',
            field=models.CharField(choices=[('BUILDING', 'Building'), ('NEEDS_REVIEW', 'Needs review'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('FAILED', 'Failed')], default='BUILDING', max_length=20),
        ),
    ]
