# Generated by Django 5.1.15 on 2026-09-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_memory', '0003_alter_candidatememory_status'),
        ('llm_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkExtractionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_sha256', models.CharField(editable=False, help_text="Snapshot of the source document's content hash at attempt time.", max_length=64)),
                ('start_line', models.PositiveIntegerField()),
                ('end_line', models.PositiveIntegerField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SUPERSEDED', 'Superseded')], max_length=20)),
                ('error_category', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_attempts', to='candidate_memory.candidatememory')),
                ('llm_call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunk_attempts', to='llm_provider.llmcalllog')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_attempts', to='candidate_memory.memorysourcedocument')),
            ],
            options={
                'ordering': ['source_document_id', 'start_line', '-created_at'],
            },
        ),
    ]
