# Generated by Django 5.1.15 on 2026-09-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_memory', '0004_chunkextractionattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkextractionattempt',
            name='end_char',
            field=models.PositiveIntegerField(blank=True, help_text='Character offset (exclusive) paired with start_char; see start_char.', null=True),
        ),
        migrations.AddField(
            model_name='chunkextractionattempt',
            name='start_char',
            field=models.PositiveIntegerField(blank=True, help_text='Character offset (inclusive, 0-based) into the single line at start_line==end_line for a sentence-level sub-line fragment (Candidate Memory recovery, 2026-09-03). Null for every whole-line-or-wider attempt -- the overwhelming majority, and every row that predates this field -- meaning start_char/end_char simply do not apply.', null=True),
        ),
    ]
