# Generated by Django 5.1.15 on 2026-09-03 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_memory', '0005_chunkextractionattempt_end_char_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_id', models.CharField(blank=True, max_length=32, unique=True)),
                ('legal_employer', models.CharField(max_length=200)),
                ('client_organization', models.CharField(blank=True, help_text='Blank when there is no separate client -- the legal employer is also the displayed employer.', max_length=200)),
                ('default_displayed_organization', models.CharField(blank=True, help_text='The organisation name a rendered resume header shows by default. Auto-filled from client_organization (or legal_employer if there is no client) on first save if left blank -- never a third, independently invented value.', max_length=200)),
                ('approved_role_title', models.CharField(max_length=200)),
                ('localized_titles', models.JSONField(blank=True, default=dict, help_text="Optional operator-approved title translations keyed by language code, e.g. {'de': 'Senior Cloud-Ingenieur'}. Never machine-translated at render time -- see title_for_language().")),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_year', models.PositiveIntegerField()),
                ('start_month', models.PositiveIntegerField(blank=True, null=True)),
                ('end_status', models.CharField(choices=[('KNOWN', 'Known end date'), ('PRESENT', 'Present (ongoing)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_month', models.PositiveIntegerField(blank=True, null=True)),
                ('presentation_mode', models.CharField(choices=[('CLIENT_CENTRIC', 'Client-centric (default)'), ('LEGAL_EMPLOYER_EXPLICIT', 'Legal employer explicit'), ('COMBINED', 'Combined')], default='CLIENT_CENTRIC', max_length=30)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_year', 'start_month'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('start_month__gte', 1), ('start_month__lte', 12)), ('start_month__isnull', True), _connector='OR'), name='career_engagement_start_month_range'), models.CheckConstraint(condition=models.Q(models.Q(('end_month__gte', 1), ('end_month__lte', 12)), ('end_month__isnull', True), _connector='OR'), name='career_engagement_end_month_range')],
            },
        ),
        migrations.CreateModel(
            name='ClaimEngagementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=10)),
                ('proposed_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('career_engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_mappings', to='candidate_memory.careerengagement')),
                ('memory_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_mappings', to='candidate_memory.memoryclaim')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('memory_claim', 'career_engagement'), name='unique_claim_engagement_pair')],
            },
        ),
    ]
