# Generated by Django 5.1.15 on 2026-09-03 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_memory', '0006_careerengagement_claimengagementmapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimengagementmapping',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='The operator who approved this mapping (set only on approval, never on rejection or proposal) -- part of the audit trail alongside reviewed_at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_claim_engagement_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimengagementmapping',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Set whenever status changes away from PROPOSED -- doubles as the approval timestamp when status=APPROVED.', null=True),
        ),
    ]
