# Generated by Django 5.1.15 on 2026-09-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_memory', '0007_claimengagementmapping_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerengagement',
            name='organization_aliases',
            field=models.JSONField(blank=True, default=list, help_text="Operator-approved alternate exact spellings/casings of legal_employer or client_organization (e.g. 'ford motors' for 'Ford Motor Werk GmbH') -- used only for deterministic claim-mapping matching (services/engagement_mapping.py). Never the canonical identity itself, which always stays legal_employer/client_organization."),
        ),
        migrations.AddField(
            model_name='careerengagement',
            name='programme_scopes',
            field=models.JSONField(blank=True, default=list, help_text="Operator-approved project/programme subject_scope values known to have occurred during this engagement (e.g. 'ford connectivity', a named initiative) -- matches a claim to this engagement without implying it is an employer/client name."),
        ),
    ]
