# Generated by Django 5.1.15 on 2026-09-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_applications', '0002_initial'),
        ('job_intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('retrieved_claim_ids', models.JSONField(blank=True, default=list, help_text='Exactly which confirmed, resume-eligible MemoryClaim IDs were retrieved and made available to Agent Candidate for this run -- an explicit, inspectable audit record of the bounded context actually provided, never the full CandidateMemory.')),
                ('retrieved_engagement_ids', models.JSONField(blank=True, default=list, help_text='Exactly which APPROVED CareerEngagement IDs were made available for this run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('based_on_jra', models.ForeignKey(help_text='The exact JobRequirementAnalysis version this assessment was built against (D-006 freshness identity -- compared against JobApplication.current_jra_id, never a timestamp).', on_delete=django.db.models.deletion.PROTECT, related_name='fit_assessments', to='job_intake.jobrequirementanalysis')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_assessments', to='job_applications.jobapplication')),
            ],
            options={
                'ordering': ['job_application_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='RequirementAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=16)),
                ('disposition', models.CharField(choices=[('MATCH', 'Match'), ('PARTIAL', 'Partial'), ('GAP', 'Gap'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('supporting_memory_claim_ids', models.JSONField(blank=True, default=list)),
                ('supporting_engagement_ids', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('gap_or_limitation', models.TextField(blank=True, default='')),
                ('fit_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_assessments', to='candidate_matching.fitassessment')),
            ],
            options={
                'ordering': ['fit_assessment_id', 'requirement_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fitassessment',
            constraint=models.UniqueConstraint(fields=('job_application', 'version'), name='unique_fit_assessment_version_per_application'),
        ),
        migrations.AddConstraint(
            model_name='requirementassessment',
            constraint=models.UniqueConstraint(fields=('fit_assessment', 'requirement_id'), name='unique_requirement_assessment_per_fit'),
        ),
    ]
