# Generated by Django 5.1.15 on 2026-09-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitassessment',
            name='retrieval_manifest',
            field=models.JSONField(blank=True, default=dict, help_text='Inspectable record of the bounded retrieval pipeline for this run (audit hardening, 2026-09-03): eligible/duplicate/candidate/selected counts, excluded-with-reason counts, per-requirement selected claim IDs, rule counts, the estimated request token size, and the cap configuration in effect -- see candidate_matching.services.bounded_retrieval.RetrievalManifest. Never raw provider prompts or responses.'),
        ),
    ]
