# Generated by Django 5.1.15 on 2026-09-07 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_matching', '0002_fitassessment_retrieval_manifest'),
        ('candidate_memory', '0008_careerengagement_organization_aliases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitassessment',
            name='based_on_candidate_memory',
            field=models.ForeignKey(blank=True, help_text="D-037 pinned-evidence-identity correction: the exact CandidateMemory revision that was ACTIVE when this FitAssessment was created -- the frozen identity Agent Builder (M6) must use for this assessment forever after, regardless of which CandidateMemory revision is ACTIVE at M6 execution time. Nullable only for pre-D-037 legacy rows (e.g. FitAssessment id 9), which never recorded this identity and therefore have no valid baseline_chronology_manifest either -- every FitAssessment created through candidate_matching.services.fit_assessment.build_fit_assessment from this correction onward always sets this field; the production M6 path (resume_builder.services.context.build_builder_context) fails closed on a legacy row with this field null rather than treating null as 'use whatever is ACTIVE now'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fit_assessments', to='candidate_memory.candidatememory'),
        ),
        migrations.AddField(
            model_name='fitassessment',
            name='baseline_chronology_manifest',
            field=models.JSONField(blank=True, default=dict, help_text="D-037 pinned-evidence-identity correction: the deterministic, zero-LLM baseline-chronology manifest computed once, at this FitAssessment's own creation time, against based_on_candidate_memory and the CareerEngagement/ClaimEngagementMapping state as it stood at that exact moment -- see candidate_matching.services.baseline_chronology.build_baseline_manifest for the schema and candidate_matching.services.fit_assessment for where it is computed and persisted atomically with this row. Never recomputed at M6 time: resume_builder.services.context.build_builder_context reads this exact persisted value, never live CareerEngagement.approval_status/ClaimEngagementMapping.status/the currently ACTIVE CandidateMemory. An empty dict (the default) means 'no manifest recorded' -- true only for pre-D-037 legacy rows; a row created after this correction always has a non-empty, schema-validated manifest."),
        ),
    ]
