# Generated by Django 5.1.15 on 2026-09-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_matching', '0003_fitassessment_based_on_candidate_memory'),
        ('candidate_memory', '0008_careerengagement_organization_aliases_and_more'),
        ('job_applications', '0004_jobapplication_current_resume_draft'),
        ('job_intake', '0001_initial'),
        ('llm_provider', '0010_default_reasoning_effort'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCandidateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=12)),
                ('baseline_chronology_manifest', models.JSONField(blank=True, default=dict, help_text='Computed once, at AC_RANK-approval time (Phase E), independent of which claims AC_RANK itself selected -- see candidate_matching.services.baseline_chronology. Copied verbatim onto FitAssessment.baseline_chronology_manifest at finalization.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('based_on_candidate_memory', models.ForeignKey(help_text="The CandidateMemory revision that was ACTIVE when this run started -- pinned for the run's entire lifetime, mirroring FitAssessment.based_on_candidate_memory (D-037). A later CandidateMemory activation never changes what an in-progress or completed run is judged against.", on_delete=django.db.models.deletion.PROTECT, related_name='agent_candidate_runs', to='candidate_memory.candidatememory')),
                ('based_on_jra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_candidate_runs', to='job_intake.jobrequirementanalysis')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_candidate_runs', to='job_applications.jobapplication')),
                ('resulting_fit_assessment', models.ForeignKey(blank=True, help_text='Set only by finalize_run, atomically with FitAssessment creation. Null for every run that has not yet reached AC_MATCH approval + explicit finalization.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_candidate_run', to='candidate_matching.fitassessment')),
            ],
            options={
                'ordering': ['job_application_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='AgentCandidateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('AC_NORMALIZE', 'Agent Candidate - Requirement Normalization (bounded query expansion, D-015/D-020)'), ('AC_RANK', 'Agent Candidate - Relevance Ranking (D-015 bounded step)'), ('AC_MATCH', 'Agent Candidate - Match')], max_length=20)),
                ('stage_order', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (blocked -- a prior stage is not yet approved)'), ('READY', 'Ready to run'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('EDITED', 'Edited (operator output differs from provider output)'), ('APPROVED', 'Approved'), ('INVALIDATED', 'Invalidated (an upstream stage was re-edited)')], default='DRAFT', max_length=12)),
                ('prepared_input', models.JSONField(blank=True, help_text='The deterministically-computed input for this stage (never touches canonical JobRequirement/MemoryClaim/CandidateMemory/JobRequirementAnalysis records -- a run-local snapshot only). Set once, when the stage becomes READY; immutable thereafter -- an operator edit is layered on top via edited_input, never written back here.', null=True)),
                ('edited_input', models.JSONField(blank=True, help_text="The operator's current edit of prepared_input, or null if unedited. The *effective* input this stage's provider call actually uses is edited_input if set, else prepared_input.", null=True)),
                ('input_hash', models.CharField(blank=True, help_text='sha256 of the effective input actually sent, recorded at execution time.', max_length=64)),
                ('selection_source', models.CharField(blank=True, choices=[('DEFAULT', 'Stage default (StageModelAssignment)'), ('OVERRIDE', 'Explicit per-run override')], max_length=10)),
                ('reasoning_effort', models.CharField(blank=True, max_length=10)),
                ('requested_output_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_output_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_output', models.JSONField(blank=True, help_text='The immutable, original structured provider output (schema-validated). Never overwritten once set -- an operator edit is stored in operator_output/revisions, never here.', null=True)),
                ('provider_output_hash', models.CharField(blank=True, max_length=64)),
                ('operator_output', models.JSONField(blank=True, help_text='The current editable copy -- starts as a plain copy of provider_output on SUCCEEDED, may be edited any number of times (each edit recorded as a new AgentCandidateStageRevision, never deleting a prior one).', null=True)),
                ('approved_output', models.JSONField(blank=True, help_text='A frozen copy of operator_output at the moment of approval. Never mutated after approval -- a later edit invalidates the approval (status back to EDITED/DRAFT for downstream) rather than changing this field in place.', null=True)),
                ('approved_output_hash', models.CharField(blank=True, max_length=64)),
                ('validation_state', models.CharField(blank=True, choices=[('UNVALIDATED', 'Not yet validated'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='UNVALIDATED', max_length=12)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('failure_category', models.CharField(blank=True, max_length=20)),
                ('failure_summary', models.TextField(blank=True, help_text='Sanitized message only -- never raw provider request/response content.')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0, help_text='Optimistic-concurrency guard: every mutating service call must be given the lock_version it last read and increments it on success; a stale value raises ConcurrentStageModificationError rather than silently overwriting a concurrent change.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_candidate_stages', to='llm_provider.llmcalllog')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='candidate_matching.agentcandidaterun')),
                ('selected_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='llm_provider.llmmodel')),
                ('selected_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='llm_provider.llmprovider')),
            ],
            options={
                'ordering': ['run_id', 'stage_order'],
            },
        ),
        migrations.CreateModel(
            name='AgentCandidateStageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INPUT', 'Input edit'), ('OUTPUT', 'Output edit')], max_length=10)),
                ('revision_number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('validation_state', models.CharField(blank=True, max_length=12)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='candidate_matching.agentcandidatestage')),
            ],
            options={
                'ordering': ['stage_id', 'kind', 'revision_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentcandidaterun',
            constraint=models.UniqueConstraint(fields=('job_application', 'version'), name='unique_ac_run_version_per_application'),
        ),
        migrations.AddConstraint(
            model_name='agentcandidatestage',
            constraint=models.UniqueConstraint(fields=('run', 'stage'), name='unique_stage_per_run'),
        ),
        migrations.AddConstraint(
            model_name='agentcandidatestage',
            constraint=models.UniqueConstraint(fields=('run', 'stage_order'), name='unique_stage_order_per_run'),
        ),
        migrations.AddConstraint(
            model_name='agentcandidatestage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), ('validation_state', 'VALID'), _connector='OR'), name='approved_stage_requires_valid_output'),
        ),
        migrations.AddConstraint(
            model_name='agentcandidatestagerevision',
            constraint=models.UniqueConstraint(fields=('stage', 'kind', 'revision_number'), name='unique_stage_revision'),
        ),
    ]
